title: "Saif Mahmud"
tagline: "Software Engineering • Machine Learning • Explainable AI"
description: "PhD student at UTA. Research interests: Software Engineering, Machine Learning, Explainable AI."
url: "https://saif0524.github.io"
baseurl: ""
theme: minima
author:
  name: "Saif Mahmud"
  email: sxm8931@mavs.uta.edu
  affiliation: "PhD Student, Computer Science, University of Texas at Arlington"
  google_scholar: ""  # add if available
  orcid: ""           # add if available
  github: "https://github.com/saif0524"
  linkedin: "https://www.linkedin.com/in/saif--mahmud"
permalink: /:categories/:title/
collections:
  posts:
    output: true
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/saif0524" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/saif--mahmud" }
header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - contact.md
plugins: []
markdown: kramdown
kramdown:
  input: GFM
google_analytics: ""
